### ISSUE TITLE
How to clean the search from code?

### ISSUE THREAD

**Issue by fcogutierrez** [stidges/jquery-searchable#12]
Hi guys.

Is it possible to clean the search from code?

If I do `$('#burgerSearchInput').val('')` the search is not reset.

How can I do it?

**Comment by stidges** [comment]
You can manually trigger the search by calling `$('#burgerSearchInput').trigger('change');` after clearing the value. Let me know if this resolves your issue!

I may introduce a clearer way to do this in the next version (e.g. `$('.element').searchable('reset')` or something similar).

**Comment by fcogutierrez** [comment]
It works!! Thank you a lot, @stidges!! :)

**Comment by stidges** [comment]
Glad to hear, you're welcome!
