### ISSUE TITLE
Suddenly stopped working when moved to new site

### ISSUE THREAD

**Issue by zubes** [stidges/jquery-searchable#15]
I have been using this for a couple months now, and has always worked great!

However, today i transferred my webpage to a new location, and suddenly the script stopped working.

I have verified that all files are correctly in place, and no additional code was changed / altered, so i expected this to work without a hitch.

I will note... the script was previously used on non secure site.  Now, i am on a secure site behind a security certificate.  Would that have caused the script to stop working?

**Comment by stidges** [comment]
Hmm, that's strange. Adding a certificate should not make a difference. Did you double check you are referencing the script by using https:// as well?

**Comment by zubes** [comment]
i did consider that, and that was the first thing i checked.

I even switched the link to the script to the following, and it still didn't work:
//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js

It must be something on the server end.  But its weird b/c its still on the same server, just under a different domain.

**Comment by stidges** [comment]
What's not working? Are you seeing any errors in the console?

**Comment by zubes** [comment]
wow, thank you for recommending that.  I didnt even think to look there for some reason.

a completely different script was linked via a non https:// address... which caused it to crap out.  Now it works like it did!  Thanks so much!

**Comment by stidges** [comment]
No problem, glad that it was resolved :)
