### ISSUE TITLE
oddRow/evenRow when displayed at hidden div

### ISSUE THREAD

**Issue by ericsobral** [stidges/jquery-searchable#4]
The effect oddRow/evenRow doesn't work when the table is inside a hidden div (tabulation for example).

Edit: Fix found. Original code:
d=this.settings.selector+":visible";
Changed code:
d=this.settings.selector;

**Comment by stidges** [comment]
Instead of using the `:visible` selector I'm going to check the display property on the elements, this should always reflect that specific element's visiblity

**Comment by stidges** [comment]
This fix will be available in v2.0.0
