### ISSUE TITLE
Search in menu & submenu with JQuery Searchable plugin - multilevel

### ISSUE THREAD

**Issue by essivision** [stidges/jquery-searchable#6]
I want to search in menu title and submenu, but in JQuery Searchable Plugin can't find this option. When I type characters, I can find menu but can't find submenu. Searchable plugin has childSelector option but this option is searching just the first level.

http://stackoverflow.com/questions/29799273/search-in-menu-submenu-with-jquery-searchable-plugin-multilevel

**Comment by AfzalH** [comment]
Posted a solution on SO
Let me know if that works

**Comment by stidges** [comment]
It seems that this issue has been resolved on StackOverflow, so closing this now.
