### ISSUE TITLE
Possible to search with multiple inputs? Or manually trigger the search?

### ISSUE THREAD

**Issue by gladwinput** [stidges/jquery-searchable#7]
Hey this is a great tool - but I wondered if it was possible to use it to filter through with further inputs.

For example if you have your regular #search-input for example. But on further search you wanted to filter by another class and input.

E.g:
<input id="search-input" class="form-control" type="text" placeholder="Search">
<select id="search-subject" name="cat" class="form-control">
    <option>All</option>
    <option>Accounting</option>
</select>

So your items searched through what was typed in search-input. But when you select a search-subject option it would refilter and drill down further.

I could do this manually with:
$('.element').each(function(){
if($(this).is(':visible')){
    if($(this).find('.subject').text() != $('#search-subject').val()) {
        $(this).hide();
       //manually trigger search
    }
else if($(this).find('.subject').text() == $('#search-subject').val()) {
    $(this).show();
    //manually trigger search
}
});
But I would need to re-trigger the search to re-apply the original filter.
Is there a way to do that?

**Comment by stidges** [comment]
You can manually trigger the search by calling `$('#search-input').trigger('change')`. Let me know if this resolves your issue!
